name: hottakes1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.1
  firebase_core: "^0.5.3"
  firebase_auth: "^0.18.4+1" 
  provider: ^4.3.2+3
  cloud_firestore: ^0.14.4
  flutter_spinkit: "^4.1.2"
  flutter_launcher_icons: ^0.8.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter_icons:
  image_path: "assets/icon.png" 
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/fireicon.png
  - assets/logohor.png
  - assets/fire.svg
  - assets/cash.png
  - assets/tickets.png
  - assets/beercard.png
  - assets/merch.png
  - assets/nba/76e.png
  - assets/nba/buck.png
  - assets/nba/bul.png
  - assets/nba/cav.png
  - assets/nba/cel.png
  - assets/nba/cli.png
  - assets/nba/gri.png
  - assets/nba/haw.png
  - assets/nba/hea.png
  - assets/nba/hor.png
  - assets/nba/hroc.png
  - assets/nba/jaz.png
  - assets/nba/kni.png
  - assets/nba/lak.png
  - assets/nba/mag.png
  - assets/nba/mav.png
  - assets/nba/net.png
  - assets/nba/nug.png
  - assets/nba/pace.png
  - assets/nba/pel.png
  - assets/nba/pis.png
  - assets/nba/rap.png
  - assets/nba/skin.png
  - assets/nba/spu.png
  - assets/nba/sun.png
  - assets/nba/thu.png
  - assets/nba/tim.png
  - assets/nba/tra.png
  - assets/nba/war.png
  - assets/nba/wiz.png
  - assets/nba/pat.png
  - assets/nba/bron.png
  - assets/nba/49e.png
  - assets/nba/49e.png
  - assets/nba/ang.png
  - assets/nba/ast.png
  - assets/nba/ath.png
  - assets/nba/ava.png
  - assets/nba/bea.png
  - assets/nba/ben.png
  - assets/nba/ben.png
  - assets/nba/bil.png
  - assets/nba/bla.png
  - assets/nba/blja.png
  - assets/nba/blue.png
  - assets/nba/bluj.png
  - assets/nba/bra.png
  - assets/nba/bre.png
  - assets/nba/brow.png
  - assets/nba/bru.png
  - assets/nba/bucc.png
  - assets/nba/cana.png
  - assets/nba/canu.png
  - assets/nba/cap.png
  - assets/nba/acar.png
  - assets/nba/cha.png
  - assets/nba/chi.png
  - assets/nba/col.png
  - assets/nba/cow.png
  - assets/nba/coy.png
  - assets/nba/cpan.png
  - assets/nba/croc.png
  - assets/nba/cub.png
  - assets/nba/dev.png
  - assets/nba/dia.png
  - assets/nba/dod.png
  - assets/nba/dol.png
  - assets/nba/duc.png
  - assets/nba/eag.png
  - assets/nba/fal.png
  - assets/nba/fla.png
  - assets/nba/fly.png
  - assets/nba/foo.png
  - assets/nba/fpan.png
  - assets/nba/gol.png
  - assets/nba/hur.png
  - assets/nba/ind.png
  - assets/nba/isl.png
  - assets/nba/jag.png
  - assets/nba/map.png
  - assets/nba/lig.png
  - assets/nba/lio.png
  - assets/nba/lkin.png
  - assets/nba/met.png
  - assets/nba/mmar.png
  - assets/nba/nat.png
  - assets/nba/ngia.png
  - assets/nba/njet.png
  - assets/nba/nran.png
  - assets/nba/oil.png
  - assets/nba/ori.png
  - assets/nba/pack.png
  - assets/nba/pad.png
  - assets/nba/pen.png
  - assets/nba/phi.png
  - assets/nba/pir.png
  - assets/nba/pre.png
  - assets/nba/rai.png
  - assets/nba/ram.png
  - assets/nba/rav.png
  - assets/nba/ray.png
  - assets/nba/rdso.png
  - assets/nba/rdwi.png
  - assets/nba/reds.png
  - assets/nba/roy.png
  - assets/nba/sab.png
  - assets/nba/sai.png
  - assets/nba/scar.png
  - assets/nba/sea.png
  - assets/nba/sen.png
  - assets/nba/sgia.png
  - assets/nba/sha.png
  - assets/nba/smar.png
  - assets/nba/sta.png
  - assets/nba/ste.png
  - assets/nba/tex.png
  - assets/nba/tig.png
  - assets/nba/tit.png
  - assets/nba/tran.png
  - assets/nba/twi.png
  - assets/nba/vik.png
  - assets/nba/whi.png
  - assets/nba/wil.png
  - assets/nba/wjet.png
  - assets/nba/yan.png




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family:  FireIcon
    fonts:
      - asset: fonts/FireIcon.ttf
  - family: SFProDisplay 
    fonts:
      - asset: fonts/SFProDisplay.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
